### ISSUE TITLE
Gitee-go，在复制使用你的脚本时，依然看不到流水线任务生成

### ISSUE THREAD

**Issue by lololowe** [wangxinleo/wechat-public-account-push#310]
按照图文教程完整配置后依然无法定时自动运行Gitee的流水线任务

**Comment by wangxinleo** [comment]
能不能贴一下具体遇到问题的地方

**Comment by wangxinleo** [comment]
如果是流水线不出来。可以尝试一下在流水线代码模式下，加入以下代码。就会出现流水线了。
![image](https://user-images.githubusercontent.com/28293988/219681596-34a87198-350f-4baa-8140-758c021e01a2.png)

```
  push:
  branches:
    prefix:
      - master
```
